name: CI
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EMAIL_TRACKING_BACKEND_URL: ${{ secrets.EMAIL_TRACKING_BACKEND_URL }}
      EMAIL_TRACKING_BACKEND_URL_OLD: ${{ secrets.EMAIL_TRACKING_BACKEND_URL_OLD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          # https://github.com/actions/setup-node/issues/467
          node-version: 18
          cache: 'npm'
      - run: mkdir node_modules && npm ci --no-fund --no-audit
      - run: npm test
      - name: Build Release
        run: |
          npm run build
          ls ./build
        env:
          EMAIL_TRACKING_BACKEND_URL: ${{ secrets.EMAIL_TRACKING_BACKEND_URL }}
          EMAIL_TRACKING_BACKEND_URL_OLD: ${{ secrets.EMAIL_TRACKING_BACKEND_URL_OLD }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        if: github.ref == 'refs/heads/master'
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
        with:
          environment: production
          sourcemaps: ./build
          url_prefix: chrome-extension://${{ secrets.CHROME_EXTENSION_ID }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build/*
